[manifest]
version = "1.0.0"
dump_lua = true
priority = -999

[[patches]]
[patches.pattern]
target = "functions/stat_events.lua"
pattern = '''
play_area_status_text("Not Allowed!")--localize('k_not_allowed_ex'), true)'''
position = "at"
payload = '''
play_area_status_text("不允许！")--localize('k_not_allowed_ex'), true)'''
match_indent = true

# 减缓卡牌名称渐入效果以适应中文牌名普遍长度
[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/utils.lua"]'
pattern = "pop_in_rate = (not args.no_pop_in and (args.pop_in_rate or 4)) or nil,"
position = "at"
payload = "pop_in_rate = (not args.no_pop_in and (args.pop_in_rate or 1)) or nil,"
match_indent = true

[[patches]]
[patches.regex]
target = '=[SMODS allinjest "Items/Tag/Gold/nonstandard.lua"]'
pattern = '"Set Suit"'
position = "at"
payload = '"设定花色"'

[[patches]]
[patches.regex]
target = '=[SMODS allinjest "Items/Tag/Gold/nonstandard.lua"]'
pattern = '"Set Rank"'
position = "at"
payload = '"设定点数"'

[[patches]]
[patches.regex]
target = '=[SMODS allinjest "Items/Tag/Gold/nonstandard.lua"]'
pattern = '"Enhancement"'
position = "at"
payload = '"增强"'

[[patches]]
[patches.regex]
target = '=[SMODS allinjest "Items/Tag/Gold/nonstandard.lua"]'
pattern = 'label = "Edition"'
position = "at"
payload = 'label = "版本"'

[[patches]]
[patches.regex]
target = '=[SMODS allinjest "Items/Tag/Gold/nonstandard.lua"]'
pattern = '"Seal"'
position = "at"
payload = '"蜡封"'

[[patches]]
[patches.pattern]
target = '=[SMODS allinjest "Utils/functions.lua"]'
pattern = '''
local destroy_texts = {
'''
position = "after"
payload = '''
"摧毁",
"自毁",
'''
match_indent = true

[[patches]]
[patches.regex]
target = '=[SMODS allinjest "Utils/ui.lua"]'
pattern = 'text = "Select"'
position = "at"
payload = 'text = "选择"'

[[patches]]
[patches.pattern]
target = '=[SMODS allinjest "Items/Crossmod/Partners/flub.lua"]'
pattern = '''
    local benefits = 'half price'
    if link_level == 1 then benefits = 'free' end
'''
position = "at"
payload = '''
    local benefits = '半价'
    if link_level == 1 then benefits = '免费' end
'''
match_indent = true

[[patches]]
[patches.regex]
target = '=[SMODS allinjest "Items/Jokers/stock_broker.lua"]'
pattern = '"X"..tostring(ran_amount.." Interest")'
position = "at"
payload = '"利息X"..tostring(ran_amount)'

[[patches]]
[patches.pattern]
target = '=[SMODS SealsOnEverything "main.lua"]'
pattern = '''
                    name =  ((not v.original_mod) and localize({type = 'name_text', key = k, set = 'Planet'})..' Joker') or '',
                    text = {
                        "If played {C:attention}poker hand{} is",
                        "{C:attention}#1#{}",
                        "Upgrade played hand",
'''
position = "at"
payload = '''
                    name =  ((not v.original_mod) and localize({type = 'name_text', key = k, set = 'Planet'})..'小丑') or '',
                    text = {
                        "若所出{C:attention}牌型{}为{C:attention}#1#",
                        "升级该牌型",
'''
match_indent = true

[[patches]]
[patches.regex]
target = '=[SMODS SealsOnEverything "synonyms/consumeables/vice.lua"]'
pattern = "'Joker' or 'Jokers'"
position = "at"
payload = "'小丑牌' or '小丑牌'"

[[patches]]
[patches.regex]
target = '=[SMODS SealsOnEverything "main.lua"]'
pattern = "'Nothing'"
position = "at"
payload = "'无'"

[[patches]]
[patches.regex]
target = '=[SMODS Incantation "Incantation.lua"]'
pattern = "'BULK USE'"
position = "at"
payload = "'批量使用'"

[[patches]]
[patches.regex]
target = '=[SMODS Incantation "Incantation.lua"]'
pattern = "'BULK USE (ONE-AT-A-TIME)'"
position = "at"
payload = "'批量使用（逐一）'"

[[patches]] # ts aint working
[patches.pattern]
target = '=[SMODS Saturn "core/logic/stack.lua"]'
pattern = '''
text = "USE ALL",
'''
position = "at"
payload = '''
text = "全部使用",
'''
match_indent = true

[[patches]] # ts aint working
[patches.pattern]
target = '=[SMODS Saturn "core/logic/stack.lua"]'
pattern = '''
text = "SELL ALL",
'''
position = "at"
payload = '''
text = "全部售出",
'''
match_indent = true

[[patches]]
[patches.pattern]
target = '=[SMODS RiftRaft "src/RiftRaft.lua"]'
pattern = '''
name = "Wormhole",
text = {
"{C:attention}Shop{} cards can be",
"sent to the {C:riftraft_void}Void{}",
"for their original",
"price",
'''
position = "at"
payload = '''
name = "虫洞跃迁",
text = {
"可支付原价",
"使{C:attention}商店{}内的卡牌",
"堕入{C:riftraft_void}虚空"
'''
match_indent = true

[[patches]]
[patches.pattern]
target = '=[SMODS RiftRaft "src/RiftRaft.lua"]'
pattern = '''
name = "Wormhole",
text = {
"{C:attention}Shop{} cards can be",
"sent to the {C:riftraft_void}Void{}",
'''
position = "at"
payload = '''
name = "虫洞跃迁",
text = {
"可使{C:attention}商店{}内的卡牌",
"堕入{C:riftraft_void}虚空",
'''
match_indent = true

[[patches]]
[patches.pattern]
target = '=[SMODS RiftRaft "src/VoidPacks.lua"]'
pattern = '''
{"Void Pack", 1, 3, 2, 1},
{"Void Pack", 1, 3, 2, 1},
{"Jumbo Void Pack", 1, 5, 4, 1},
{"Mega Void Pack", 2, 5, 7, 0.25},
'''
position = "at"
payload = '''
{"虚空包", 1, 3, 2, 1},
{"虚空包", 1, 3, 2, 1},
{"巨型虚空包", 1, 5, 4, 1},
{"超级虚空包", 2, 5, 7, 0.25},
'''
match_indent = true

[[patches]]
[patches.pattern]
target = '=[SMODS RiftRaft "src/VoidPacks.lua"]'
pattern = '''
"Choose {C:attention}#1#{} of up to",
"{C:attention}#2#{C:riftraft_void} Rift{} cards to",
"be used immediately",
},
group_name = "Void Pack",
'''
position = "at"
payload = '''
"从{C:attention}#2#{}张{C:riftraft_void}裂隙{}牌中",
"选择{C:attention}#1#{}张并立即使用",
},
group_name = "虚空包",
'''
match_indent = true

[[patches]]
[patches.pattern]
target = '=[SMODS RiftRaft "src/Vouchers.lua"]'
pattern = '''
name = "Microtransaction",
text = {
"{C:attention}+1{} booster pack",
"per {C:attention}shop{}",
'''
position = "at"
payload = '''
name = "微交易",
text = {
"{C:attention}商店{}提供的",
"补充包数量{C:attention}+1"
'''
match_indent = true

[[patches]]
[patches.pattern]
target = '=[SMODS RiftRaft "src/Vouchers.lua"]'
pattern = '''
name = "Microtransaction",
text = {
"{C:attention}+1{} booster pack",
"per {C:attention}shop{},",
"shop always has",
"a {C:riftraft_void}Void{} Pack",
'''
position = "at"
payload = '''
name = "微交易",
text = {
"{C:attention}商店{}提供的",
"补充包数量{C:attention}+1",
"商店恒提供一个{C:riftraft_void}虚空{}包"
'''
match_indent = true
