# https://github.com/marketplace/actions/easy-zip-files

name: 🗂️ Zip file for ModLoaders
on: workflow_dispatch
jobs:
  zip-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Zip files
      run: |
        zip -r better_FR.zip localization/fr.lua localization/Better_FR.lua
    - name: Upload to FTP
      uses: pressidium/lftp-mirror-action@v1
      with:
        host: ${{ secrets.FTP_HOST }}
        user: ${{ secrets.FTP_LOGIN }}
        pass: ${{ secrets.FTP_PASSWORD }}
        local-dir: better_FR.zip
        remote-dir: /www/
        upload: true