# https://github.com/marketplace/actions/easy-zip-files

name: 🗂️ Zip file for ModLoaders
on: workflow_dispatch
jobs:
  zip:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: vimtor/action-zip@v1.1
      with:
        files: localization/fr.lua localization/Better_FR.lua
        dest: BetterFR.zip
    - uses: sokuhatiku/ftp-upload-artifact@v1.0.0
      with:
        name: BetterFR.zip
        path: BetterFR.zip
        host: ${{ secrets.FTP_HOST }}
        port: 22
        username: ${{ secrets.FTP_LOGIN }}
        password: ${{ secrets.FTP_PASSWORD }}
        secure: true
        remote-path: /www